{
    "id": "dbpedia_8287_3",
    "rank": 99,
    "data": {
        "url": "https://forums.autodesk.com/t5/visual-lisp-autolisp-and-general/customizing-azimuth-distance-display-for-automated-survey-plats/td-p/12942428",
        "read_more_link": "",
        "language": "en",
        "title": "Customizing azimuth/distance display for automated survey plats",
        "top_image": "https://forums.autodesk.com/t5/image/serverpage/image-id/1394904i37D4F03F5C8A9B15?v=v2",
        "meta_img": "https://forums.autodesk.com/t5/image/serverpage/image-id/1394904i37D4F03F5C8A9B15?v=v2",
        "images": [
            "https://forums.autodesk.com/html/@E3EF46B230710BF938EDB3C46A0BE159/assets/machine-translation-info-icon.png",
            "https://forums.autodesk.com/t5/image/serverpage/avatar-name/default/avatar-theme/chrome/avatar-collection/Default/avatar-display-size/unspecified/version/2?xdesc=1.0",
            "https://forums.autodesk.com/html/@4AF0D5778CA8F669245BE7852AAAD971/rank_icons/5.png",
            "https://forums.autodesk.com/t5/image/serverpage/image-id/1394904i37D4F03F5C8A9B15/image-size/medium?v=v2&px=400",
            "https://forums.autodesk.com/t5/image/serverpage/image-id/1394905iF69A63523952F4F8/image-size/medium?v=v2&px=400",
            "https://forums.autodesk.com/t5/image/serverpage/avatar-name/default/avatar-theme/chrome/avatar-collection/Default/avatar-display-size/unspecified/version/2?xdesc=1.0",
            "https://forums.autodesk.com/html/@8FD10A6A1378FD5C56E7E603906384B5/rank_icons/11.png",
            "https://forums.autodesk.com/t5/image/serverpage/avatar-name/default/avatar-theme/chrome/avatar-collection/Default/avatar-display-size/unspecified/version/2?xdesc=1.0",
            "https://forums.autodesk.com/html/@4AF0D5778CA8F669245BE7852AAAD971/rank_icons/5.png",
            "https://forums.autodesk.com/t5/image/serverpage/avatar-name/default/avatar-theme/chrome/avatar-collection/Default/avatar-display-size/unspecified/version/2?xdesc=1.0",
            "https://forums.autodesk.com/html/@4AF0D5778CA8F669245BE7852AAAD971/rank_icons/5.png",
            "https://forums.autodesk.com/html/@29151EA02A096B7351A6AEA726D33D94/emoticons/1f642.png",
            "https://images.profile.autodesk.com/200809200362017/profilepictures/x176.jpg?r=637414024814490000",
            "https://forums.autodesk.com/html/@2CC91153AA154404ACE045289CF09EB3/rank_icons/12.png",
            "https://forums.autodesk.com/t5/image/serverpage/image-id/962943iDF6D27C26CA3B56D/image-size/small?v=v2&px=300%22",
            "https://forums.autodesk.com/t5/image/serverpage/avatar-name/default/avatar-theme/chrome/avatar-collection/Default/avatar-display-size/unspecified/version/2?xdesc=1.0",
            "https://forums.autodesk.com/html/@4AF0D5778CA8F669245BE7852AAAD971/rank_icons/5.png",
            "https://forums.autodesk.com/t5/image/serverpage/avatar-name/default/avatar-theme/chrome/avatar-collection/Default/avatar-display-size/unspecified/version/2?xdesc=1.0",
            "https://forums.autodesk.com/html/@4AF0D5778CA8F669245BE7852AAAD971/rank_icons/5.png",
            "https://forums.autodesk.com/t5/image/serverpage/avatar-name/default/avatar-theme/chrome/avatar-collection/Default/avatar-display-size/unspecified/version/2?xdesc=1.0",
            "https://forums.autodesk.com/html/@4AF0D5778CA8F669245BE7852AAAD971/rank_icons/5.png",
            "https://images.profile.autodesk.com/200809200362017/profilepictures/x176.jpg?r=637414024814490000",
            "https://forums.autodesk.com/html/@2CC91153AA154404ACE045289CF09EB3/rank_icons/12.png",
            "https://forums.autodesk.com/t5/image/serverpage/image-id/962943iDF6D27C26CA3B56D/image-size/small?v=v2&px=300%22",
            "https://forums.autodesk.com/skins/images/9DBBCB5DAFD45F48033C3752084F2F25/responsive_peak/images/icon_anonymous_message.png",
            "https://forums.autodesk.com/skins/images/9DBBCB5DAFD45F48033C3752084F2F25/responsive_peak/images/icon_anonymous_message.png",
            "https://forums.autodesk.com/t5/image/serverpage/image-id/1393398i4EC8213BB09F7F26/image-size/large?v=v2&px=999",
            "https://forums.autodesk.com/t5/image/serverpage/image-id/1390673i1F8DC40828EB2819/image-size/large?v=v2&px=999"
        ],
        "movies": [],
        "keywords": [],
        "meta_keywords": [
            ""
        ],
        "tags": null,
        "authors": [
            "buchistyle",
            "forums.autodesk.com",
            "user-id"
        ],
        "publish_date": "2024-08-06T16:03:45+00:00",
        "summary": "",
        "meta_description": "Hello, Please I have the code below which I have been using for several years. I got the code from this forum and after some modifications it has",
        "meta_lang": "en",
        "meta_favicon": "https://damassets.autodesk.net/content/dam/autodesk/logos/autodesk-symbol-32x32.svg",
        "meta_site_name": "Autodesk Community",
        "canonical_link": "https://forums.autodesk.com/t5/visual-lisp-autolisp-and-general/customizing-azimuth-distance-display-for-automated-survey-plats/td-p/12942428",
        "text": "Hello,\n\nPlease I have the code below which I have been using for several years. I got the code from this forum and after some modifications it has served me just fine. The code is:\n\n(vl-load-com)\n\n(defun c:brg69 ( / l_var js htx AcDoc Space ss nw_style n obj ename pr dist_start dist_end pt_start pt_end seg_len alpha val_txt dim_txt nw_obj)\n\n(setq l_var (mapcar 'getvar '(\"AUNITS\" \"AUPREC\" \"LUPREC\" \"LUNITS\")))\n\n(mapcar 'setvar '(\"AUNITS\" \"AUPREC\" \"LUPREC\" \"LUNITS\") '(1 2 2 2))\n\n(princ \"\\nSelect polylines or lines.\")\n\n(while (null (setq js (ssget '((0 . \"LWPOLYLINE,LINE\")))))\n\n(princ \"\\nSelection is empty or not are LWPOLYLINE,LINE!\")\n\n)\n\n(initget 6)\n\n(setq htx (getdist (getvar \"VIEWCTR\") (strcat \"\\nSpecify text height <\" (rtos (getvar \"TEXTSIZE\")) \">: \")))\n\n(if htx (setvar \"TEXTSIZE\" htx))\n\n(setq\n\nAcDoc (vla-get-ActiveDocument (vlax-get-acad-object))\n\nSpace\n\n(if (= 1 (getvar \"CVPORT\"))\n\n(vla-get-PaperSpace AcDoc)\n\n(vla-get-ModelSpace AcDoc)\n\n)\n\nss (ssadd)\n\n)\n\n(vla-startundomark AcDoc)\n\n(cond\n\n((null (tblsearch \"LAYER\" \"DIMENSIONS\"))\n\n(vlax-put (vla-add (vla-get-layers AcDoc) \"DIMENSIONS\") 'color 7)\n\n)\n\n)\n\n(cond\n\n((null (tblsearch \"STYLE\" \"LABEL_ARIAL\"))\n\n(setq nw_style (vla-add (vla-get-textstyles AcDoc) \"LABEL_ARIAL\"))\n\n(mapcar\n\n'(lambda (pr val)\n\n(vlax-put nw_style pr val)\n\n)\n\n(list 'FontFile 'Height 'ObliqueAngle 'Width 'TextGenerationFlag)\n\n(list (strcat (getenv \"windir\") \"\\\\fonts\\\\arial.ttf\") 0.0 0.0 1.0 0.0)\n\n)\n\n)\n\n)\n\n(repeat (setq n (sslength js))\n\n(setq\n\nobj (ssname js (setq n (1- n)))\n\nename (vlax-ename->vla-object obj)\n\npr -1\n\n)\n\n(cond\n\n((eq (cdr (assoc 0 (entget obj))) \"LWPOLYLINE\")\n\n(repeat (fix (vlax-curve-getEndParam ename))\n\n(setq\n\ndist_start (vlax-curve-GetDistAtParam ename (setq pr (1+ pr)))\n\ndist_end (vlax-curve-GetDistAtParam ename (1+ pr))\n\npt_start (vlax-curve-GetPointAtParam ename pr)\n\npt_end (vlax-curve-GetPointAtParam ename (1+ pr))\n\nseg_len (- dist_end dist_start)\n\nalpha (angle (trans pt_start 0 1) (trans pt_end 0 1))\n\nval_txt (vl-string-subst \"%%d\" \"d\"(strcat (angtos alpha) \"\\\\P \" (rtos seg_len)))\n\ndim_txt (textbox (list (cons 1 val_txt)))\n\n)\n\n(if (and (> alpha (* pi 0.5)) (< alpha (* pi 1.5))) (setq alpha (+ alpha pi)))\n\n(if (> (distance (car dim_txt) (cadr dim_txt)) seg_len)\n\n(setq val_txt (vl-string-subst \"E \\\\P\" \"E \" val_txt))\n\n)\n\n(setq nw_obj\n\n(vla-addMtext Space\n\n(vlax-3d-point (setq pt (vlax-curve-GetPointAtParam ename (+ 0.5 pr))))\n\n0.0\n\nval_txt\n\n)\n\n)\n\n(mapcar\n\n'(lambda (pr val)\n\n(vlax-put nw_obj pr val)\n\n)\n\n(list 'AttachmentPoint 'Height 'DrawingDirection 'InsertionPoint 'StyleName 'Layer 'Rotation)\n\n(list 5 (getvar \"TEXTSIZE\") 5 pt \"LABEL_ARIAL\" \"DIMENSIONS\" alpha)\n\n)\n\n(setq ss (ssadd (entlast) ss))\n\n)\n\n)\n\n(T\n\n(setq\n\npt_start (vlax-curve-GetStartPoint ename)\n\npt_end (vlax-curve-GetEndPoint ename)\n\nseg_len (distance pt_start pt_end)\n\nalpha (angle (trans pt_start 0 1) (trans pt_end 0 1))\n\nval_txt (vl-string-subst \"%%d\" \"d\"(strcat (angtos alpha) \"\\\\P \" (rtos seg_len)))\n\ndim_txt (textbox (list (cons 1 val_txt)))\n\n)\n\n(if (and (> alpha (* pi 0.5)) (< alpha (* pi 1.5))) (setq alpha (+ alpha pi)))\n\n(if (> (distance (car dim_txt) (cadr dim_txt)) seg_len)\n\n(setq val_txt (vl-string-subst \"E \\\\P\" \"E \" val_txt))\n\n)\n\n(setq nw_obj\n\n(vla-addMtext Space\n\n(vlax-3d-point (setq pt (mapcar '* (mapcar '+ (vlax-curve-GetStartPoint ename) (vlax-curve-GetEndPoint ename)) '(0.5 0.5 0.5))))\n\n0.0\n\nval_txt\n\n)\n\n)\n\n(mapcar\n\n'(lambda (pr val)\n\n(vlax-put nw_obj pr val)\n\n)\n\n(list 'AttachmentPoint 'Height 'DrawingDirection 'InsertionPoint 'StyleName 'Layer 'Rotation)\n\n(list 5 (getvar \"TEXTSIZE\") 5 pt \"LABEL_ARIAL\" \"DIMENSIONS\" alpha)\n\n)\n\n(setq ss (ssadd (entlast) ss))\n\n)\n\n)\n\n)\n\n(vla-endundomark AcDoc)\n\n(mapcar 'setvar '(\"AUNITS\" \"AUPREC\" \"LUPREC\" \"LUNITS\") l_var)\n\n(sssetfirst nil ss)\n\n(prin1)\n\n)\n\nI need the azimuths to come above the distances if the line direction points from 0 degrees (North) to 180 degrees (South) and I need the distances to come above the azimuths if the given line points anywhere from 180d 01' to just below 0 degrees (or 359d 59').\n\nSo far the current result is as shown:\n\nI would like to automate the process to produce this:\n\nPlease I would very much appreciate any help given. Thanks.\n\nIt sounds to me like the which-is-over-the-other issue is going to depend on your always drawing your outlines in the same direction [clockwise vs. counter-clockwise]. Are you completely and unfailingly consistent about that in your drawing procedure? Do you ever Mirror one and spoil that?\n\nIf the outline is a Polyline, rather than separate Lines, it can have one of those pieces of information always placed inside and the other outside, whether its drawn direction is CW or CCW. Would that serve your purpose? For example, you could use the DPI command defined in DimPoly.lsp, >here<, with a Dimension Style that has both extension lines and both dimension lines suppressed, to get the lengths on the inside. It might not be too hard to modify that to add the directions on the outside, but it does depend on the boundary being one Polyline, not Lines.\n\nKent Cooper, AIA\n\nHello @Kent1Cooper,\n\nYes I am consistent in drawing lines in the clockwise direction as the correct (or intended) azimuth readings depends on that. The distance over azimuth or azimuth over distance actually doesn't depend on which (clockwise or anticlockwise) I do. One is always over the other. It only results in a forward azimuth or backward azimuth is all.\n\nI will try out your provided lisp and see how it works then I will reach out. All I can say for now is making my outlines with a polyline as opposed to lines isn't a hard sacrifice to make; actually it's no sacrifice at all. I do that sometimes with the posted lisp code and it produces the same results, lines or polylines.\n\nI appreciate. I will get back soon\n\nI don't have access to my laptop currently so I can't apply the latest suggestions but I have been engrossed by the challenge since yesterday. At a point I copied the code to an AI chatbot from You.com and did a little prompting, expecting a quick resolution to the problem as I usually get when stuck in python and can you believe it? The AI actually asked me for sometime to review the code and get back to me with modifications. I gave up waiting. So to all y'all who speak the lisp lingo I honestly and in deep humility doff my hat in respect.\n\nI have gone through the code to see if something will speak to me and I have noticed that a section of the code is repeated and I wonder why. I suspect these sections handle the logic but why the exact same syntax is what I don't understand. In @Moshe-A 's code they are lines 65 through 67 and lines 92 through 94.\n\nHow does the logic here work? Is it like\n\nif condition A:\n\nthen y\n\nelse:\n\nx\n\nOr is it more like:\n\nif condition A:\n\nthen y\n\nIf condition B:\n\nthen x\n\nIf the latter is the case, how does the code deal with identifying when a given line or polyline segment points in the direction of 0d to 180d.\n\nLines 65 and 92 of the current code seem to deal with situations where the line direction is 180d 01' to 359d 59' am I right? Is there an else or otherwise in the code to handle the other condition. Could this be the solution to the challenge?"
    }
}